package com.vaaskel.domain.common;

import com.vaaskel.domain.security.entity.User;
import com.vaaskel.repository.security.UserRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
class AbstractEntityIdGenerationTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    void idIsGeneratedOnPersist() {
        User user = new User("testuser", "password");

        User saved = userRepository.save(user);

        assertThat(saved.getId()).as("ID should be generated by JPA").isNotNull();
    }
}