services:
#    local_build:
#        image: vaaskel
#        build:
#            context: .
#            dockerfile: ./scripts/vaaskel/Dockerfile

    app:
        image: ghcr.io/${GHCR_OWNER}/vaaskel:latest
        container_name: app_int
        restart: always
        depends_on:
            - database
        environment:
            SPRING_PROFILES_ACTIVE: int
            SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/vaaskel
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        networks:
            - vaaskel_net
        ports:
            - "8081:8080"
        logging:
            options:
                max-size: "100M"

    database:
        container_name: pg
        image: postgres:latest
        shm_size: 128mb
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            - vaaskel_net
        volumes:
            - pgdata:/var/lib/postgresql
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U root" ]
          interval: 10s
          timeout: 5s
          retries: 5

networks:
    vaaskel_net:
        name: vaaskel_net

volumes:
    pgdata:
